version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: khata-postgres
    environment:
      POSTGRES_DB: khata_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: khata-backend
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/khata_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

volumes:
  postgres_data:
