spring:
  application:
    name: KhataBackend
  
  # Set the default profile so it runs as DEV locally
  profiles:
    active: dev

  google:
    client-id: 337359007063-p8ahuajr786rbnephg7krr26887silnv.apps.googleusercontent.com

server:
  port: 8082
