spring:
  application:
    name: KhataBackend
  
  # Set the default profile so it runs as DEV locally
  profiles:
    active: dev

  google:
    client-id: ${CLIENT_ID}

server:
  port: 8082

aws:
  s3:
    bucket-name: pdfurls
    region: ap-south-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
