#-------------------------------------------------------------------------------#
#        Discover additional configuration options in our documentation         #
#               https://www.jetbrains.com/help/qodana/github.html               #
#-------------------------------------------------------------------------------#

name: Qodana Configuration Upload

on:
    push:
        branches: master
    pull_request:
        branches: master
    workflow_dispatch:

jobs:
    upload-qodana-config:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Qodana Configuration Uploader
              env:
                  QODANA_CONFIGURATIONS_TOKEN: ${{ secrets.QODANA_TOKEN }}
              run: |
                  docker run --rm \
                    -v $(pwd):/workspace \
                    -w /workspace \
                    -e QODANA_CONFIGURATIONS_TOKEN=$QODANA_TOKEN \
                    jetbrains/qodana-configuration-uploader:latest \
                    --qodana-host https://qodana.cloud
